#!/bin/sh

set -e

USAGE='Usage: git cococo [options] [--] <command> [args...]

Example:

    $ git cococo sed -e s/foo/bar/g *.txt
'

echo_n() {
  printf -- '%s' "$1"
}

uncommitted_changes_are_exists() {
  test -n "$(git status --short)"
}

escape_quote_argument() {
  echo_n "$1" | sed -e "s/'/'\\\\''/g"
}

escape_one_argument() {
  need_quote=
  expr "$1" : '.*[ \$\"'\'']' > /dev/null && need_quote=1

  test -z "$need_quote" || echo_n "'"
  escape_quote_argument "$1"
  test -z "$need_quote" || echo_n "'"
}

escape_command_line() {
  escape_one_argument "$1"
  shift
  for arg in "$@"
  do
    echo_n ' '
    escape_one_argument "$arg"
  done
}

create_commit_message() {
  echo_n 'run: git cococo '
  escape_command_line "$@"
}

die_or_autostash_if_uncommitted_changes_are_exists() {
  stashed=
  uncommitted_changes_are_exists || return 0

  if test -z "$autostash"
  then
    cat <<EOF
Detects following uncommitted changes:

$(git status --short | sed -e 's|^|  |')

Run "git stash" and retry "git cococo":

  $ git stash --include-untracked &&
    git cococo $(escape_command_line "$@") &&
    git stash pop

Or, use "--autostash" option:

  $ git cococo --autostash $(escape_command_line "$@")
EOF
    exit 1
  fi

  git stash --quiet --include-untracked
  stashed=1
}

commit_uncommitted_chages() {
  if uncommitted_changes_are_exists
  then
    git add --all
    create_commit_message "$@" | git commit --quiet --file=-
  else
    echo No changes are detected.
  fi
}

pop_stash_if_autostashed() {
  test -n "$stashed" || return 0

  # If only untracked files, always output "Already up to date!".
  #
  # https://github.com/git/git/blob/v2.15.0/merge-recursive.c#L1954
  git stash pop --quiet | sed -e '/^Already up to date!$/ d'
}

main() {
  # parse git cococo options.
  autostash=
  while :
  do
    case "$1" in
      --autostash)
        autostash=1
        ;;
      -h|--help)
        echo_n "$USAGE"
        exit
        ;;
      --)
        shift
        break
        ;;
      '')
        echo_n "$USAGE" 1>&2
        exit 1
        ;;
      *)
        break
        ;;
    esac
    shift
  done

  die_or_autostash_if_uncommitted_changes_are_exists "$@"
  "$@" # run command.
  commit_uncommitted_chages "$@"
  pop_stash_if_autostashed "$@"
}

main "$@"
