name: latest-git

on:
  push:
  schedule:
    - cron: "5 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache git
        uses: actions/cache@v3.3.3
        with:
          path: ~/git-versions
          key: ${{ runner.os }}-git-latest
      - name: Cache rubygems
        uses: actions/cache@v3.3.3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-rubygems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-rubygems-
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Setup git
        run: |
          set -eux
          sudo apt install -y gettext
          ./tools/latest_git_version > /tmp/git_version.t
          git_version=$(cat /tmp/git_version.t)
          ./tools/install_git $git_version
          ls -d --sort=version ~/git-versions/* \
          | sed -e '$ d' \
          | xargs -0 rm -rf
          export PATH=$HOME/git-versions/$git_version/bin:$PATH
          git config --global user.name git-cococo
          git config --global user.email git-cococo@example.org
      - name: Install dependencies
        run: |
          set -eux
          export PATH=$HOME/git-versions/$(cat /tmp/git_version.t)/bin:$PATH
          sudo apt install -y cmake shellcheck
          gem update --system
          gem install --no-document \
            bundler \
            -v $(sed -n -e '/^BUNDLED WITH$/, /^   / p' Gemfile.lock | tail -n1)
          bundle config path vendor/bundle
          bundle install --jobs $(nproc) --retry 3
      - name: Output versions
        run: |
          set -eux
          which git
          git version
          export PATH=$HOME/git-versions/$(cat /tmp/git_version.t)/bin:$PATH
          which git
          git version
          ruby --version
          gem --version
          bundle --version
          cmake --version
          shellcheck --version
      - name: Run rake
        run: |
          set -eux
          export PATH=$HOME/git-versions/$(cat /tmp/git_version.t)/bin:$PATH
          bundle exec rake
